name: ecommerce_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  firebase_storage: ^11.5.3
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_database: ^10.3.8
  provider: ^6.0.5
  another_flushbar: ^1.12.30
  curved_navigation_bar: ^1.0.3
  image_picker: ^1.0.7
  google_sign_in: ^6.2.1
  persistent_shopping_cart: ^0.0.7
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.0.1
  flutter_stripe: ^10.1.0
  stripe_android: ^10.1.0
  http: ^1.2.1
dependency_overrides:
  stripe_android: "9.5.0+1"
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/Nike logo.png
    - images/image1.png
    - images/design1.png
    - images/Vector.png
    - images/Vector2.png
    - images/smiley.png
    - images/smiley2.png
    - images/decor.png
    - images/decor2.png
    - images/misc.png
    - images/misc2.png
    - images/sneakers.png
    - images/sneakers2.png
    - images/googlelogo.png
    - images/dialogbox.png
    - images/home.png
    - images/heart.png
    - images/notification.png
    - images/profile.png
    - images/cart.png
    - images/settings.png
    - images/orders.png
    - images/signout.png
    - images/bar.png
    - images/sliders.png
    - images/shoe1.png
    - images/phone.png
    - images/email.png
    - images/edit.png
    - images/emptycart.png
    - images/products/shoe1.png
    - images/products/shoe2.png
    - images/products/shoe3.png
    - images/products/shoe4.png
    - images/products/shoe5.png
    - images/products/shoe6.png
    - images/products/shoe7.png
    - images/products/shoe8.png
    - images/products/shoe9.png
    - images/products/shoe10.png






 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
  
    - family: Poppins-Medium
      fonts:
        - asset: fonts/poppins/Poppins-Medium.ttf      
       
    - family: Raleway-Bold
      fonts:
        - asset: fonts/Raleway/Raleway-Bold.ttf
        
    - family: Raleway-Medium
      fonts:
        - asset: fonts/Raleway/Raleway-Medium.ttf

    - family: Raleway-Regular
      fonts: 
        - asset: fonts/Raleway/Raleway-Regular.ttf
  
    - family: Raleway-SemiBold
      fonts:
        - asset: fonts/Raleway/Raleway-SemiBold.ttf

          
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
